version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - ~/Documents/programming/data/db:/data/db
    ports:
      - 27017:27017
  backend:
    build: ./backend
    restart: always
    container_name: backend
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks
    stdin_open: true
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3000:3000
      env_file:
        - ./frontend/.env
    stdin_open: true




