version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - ~/Documents/programming/data/db:/data/db
    ports:
      - 27018:27017
  backend:
    build: ./backend
    restart: always
    container_name: backend
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 8001:8000
    environment:
      - MONGO_URI=mongodb://mongo:27018/tasks
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3001:3000
    env_file:
      - ./frontend/.env
    stdin_open: true
