apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksbackenddeployment
spec:
  selector:
    matchLabels:
      app: tasksbackendlabel
  replicas: 2
  template:
    metadata:
      labels:
        app: tasksbackendlabel
    spec:
      containers:
        - name: tasksbackend
          imagePullPolicy: Never
          image: tasks-backend
          ports:
            - containerPort: 8000
